### ISSUE TITLE
research how AR and Unity work with C++

### ISSUE THREAD

**Issue by jackbateson123** [jackbateson123/AgileProject#2]
find some good videos to demonstrate setting up an AR app in unity:

https://www.bing.com/videos/riverview/relatedvideo?q=Unity+egine+using+camera+app&mid=3DD9D8B8A6C9A4BF9F1B3DD9D8B8A6C9A4BF9F1B&FORM=VIRE

**Comment by jackbateson123** [comment]
test

**Comment by joehanratty** [comment]
AR image replacement

https://www.bing.com/videos/riverview/relatedvideo?q=how%20do%20augmented%20reality%20games%20work&mid=872011FB9CCC0670136E872011FB9CCC0670136E&ajaxhist=0
